GFORTRAN module created from datamodule.f90 on Sun Sep 27 14:37:57 2009
MD5:c909d8291568de547a1b91690ff70008 -- If you edit this, you'll get what you deserve.

(() () () () () () () () () () () () () () () () () () () () () () () ()
() () ())

()

()

()

()

(2 'a' 'datamodule' 'a' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN
EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
3 'aa' 'datamodule' 'aa' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
4 'abse' 'datamodule' 'abse' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
5 'ac' 'datamodule' 'ac' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
6 'alpha1' 'datamodule' 'alpha1' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 ()
() 0 0)
7 'alpha2' 'datamodule' 'alpha2' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 ()
() 0 0)
8 'atten' 'datamodule' 'atten' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
9 'az' 'datamodule' 'az' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
10 'b' 'datamodule' 'b' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN
EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
11 'bb' 'datamodule' 'bb' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
12 'bldnum' 'datamodule' 'bldnum' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (INTEGER 8 0 0
INTEGER ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
13 'bldtype' 'datamodule' 'bldtype' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (INTEGER 8 0 0
INTEGER ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
14 'build_uin' 'datamodule' 'build_uin' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
15 'bz' 'datamodule' 'bz' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
16 'ca' 'datamodule' 'ca' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
17 'canopy_atten' 'datamodule' 'canopy_atten' 1 ((VARIABLE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION)
(REAL 8 0 0 REAL ()) 0 0 () (3 DEFERRED () () () () () ()) 0 () () 0 0)
18 'canopy_d' 'datamodule' 'canopy_d' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (2 DEFERRED () () () ()) 0 () () 0 0)
19 'canopy_ktop' 'datamodule' 'canopy_ktop' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (INTEGER 8 0 0
INTEGER ()) 0 0 () (2 DEFERRED () () () ()) 0 () () 0 0)
20 'canopy_top' 'datamodule' 'canopy_top' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (2 DEFERRED () () () ()) 0 () () 0 0)
21 'canopy_ustar' 'datamodule' 'canopy_ustar' 1 ((VARIABLE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION)
(REAL 8 0 0 REAL ()) 0 0 () (2 DEFERRED () () () ()) 0 () () 0 0)
22 'canopy_zo' 'datamodule' 'canopy_zo' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (2 DEFERRED () () () ()) 0 () () 0 0)
23 'celltype' 'datamodule' 'celltype' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (INTEGER 8 0 0
INTEGER ()) 0 0 () (3 DEFERRED () () () () () ()) 0 () () 0 0)
24 'cgamma' 'datamodule' 'cgamma' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
25 'cgroup' 'datamodule' 'cgroup' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (INTEGER 8 0 0
INTEGER ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
26 'ch' 'datamodule' 'ch' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
27 'cl' 'datamodule' 'cl' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
28 'cnum' 'datamodule' 'cnum' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (INTEGER 8 0 0 INTEGER ())
0 0 () (1 DEFERRED () ()) 0 () () 0 0)
29 'cpbaucan' 'datamodule' 'cpbaucan' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 ()
() 0 0)
30 'cpbawcan' 'datamodule' 'cpbawcan' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 ()
() 0 0)
31 'cpbbeta' 'datamodule' 'cpbbeta' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 ()
() 0 0)
32 'cpbk' 'datamodule' 'cpbk' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
33 'ctype' 'datamodule' 'ctype' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (INTEGER 8 0 0 INTEGER ())
0 0 () (1 DEFERRED () ()) 0 () () 0 0)
34 'cw' 'datamodule' 'cw' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
35 'cxfo' 'datamodule' 'cxfo' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
36 'cyfo' 'datamodule' 'cyfo' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
37 'czfo' 'datamodule' 'czfo' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
38 'd' 'datamodule' 'd' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN
EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
39 'datamodule' 'datamodule' 'datamodule' 1 ((MODULE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN UNKNOWN) (UNKNOWN 0 0 0 UNKNOWN ()) 0 0 () () 0 ()
() 0 0)
40 'denoms' 'datamodule' 'denoms' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (3 DEFERRED () () () () () ()) 0 () () 0 0)
41 'diffiter' 'datamodule' 'diffiter' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () ()
0 () () 0 0)
42 'diffstep' 'datamodule' 'diffstep' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () ()
0 () () 0 0)
43 'diffusion_flag' 'datamodule' 'diffusion_flag' 1 ((VARIABLE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0
INTEGER ()) 0 0 () () 0 () () 0 0)
44 'domain_rotation' 'datamodule' 'domain_rotation' 1 ((VARIABLE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ())
0 0 () () 0 () () 0 0)
45 'dt' 'datamodule' 'dt' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
46 'dx' 'datamodule' 'dx' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
47 'dy' 'datamodule' 'dy' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
48 'dz' 'datamodule' 'dz' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
49 'dz_array' 'datamodule' 'dz_array' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
50 'e' 'datamodule' 'e' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN
EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 () (3
DEFERRED () () () () () ()) 0 () () 0 0)
51 'eps' 'datamodule' 'eps' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
52 'eta' 'datamodule' 'eta' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
53 'f' 'datamodule' 'f' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN
EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 () (3
DEFERRED () () () () () ()) 0 () () 0 0)
54 'fdh' 'datamodule' 'fdh' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
55 'format_flag' 'datamodule' 'format_flag' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () ()
0 () () 0 0)
56 'fxd' 'datamodule' 'fxd' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(3 DEFERRED () () () () () ()) 0 () () 0 0)
57 'fyd' 'datamodule' 'fyd' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(3 DEFERRED () () () () () ()) 0 () () 0 0)
58 'fzd' 'datamodule' 'fzd' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(3 DEFERRED () () () () () ()) 0 () () 0 0)
59 'g' 'datamodule' 'g' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN
EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 () (3
DEFERRED () () () () () ()) 0 () () 0 0)
60 'gamma' 'datamodule' 'gamma' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
61 'group_id' 'datamodule' 'group_id' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (INTEGER 8 0 0
INTEGER ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
62 'h' 'datamodule' 'h' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN
EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 () (3
DEFERRED () () () () () ()) 0 () () 0 0)
63 'havx' 'datamodule' 'havx' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
64 'havy' 'datamodule' 'havy' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
65 'hdifx' 'datamodule' 'hdifx' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
66 'hdify' 'datamodule' 'hdify' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
67 'hlowx' 'datamodule' 'hlowx' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
68 'hlowy' 'datamodule' 'hlowy' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
69 'ht' 'datamodule' 'ht' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
70 'i' 'datamodule' 'i' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN
EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () () 0 () () 0 0)
71 'i_time' 'datamodule' 'i_time' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () ()
0 () () 0 0)
72 'ibldflag' 'datamodule' 'ibldflag' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (INTEGER 8 0 0
INTEGER ()) 0 0 () (3 DEFERRED () () () () () ()) 0 () () 0 0)
73 'ibuild' 'datamodule' 'ibuild' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () ()
0 () () 0 0)
74 'icellflag' 'datamodule' 'icellflag' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (INTEGER 8 0 0
INTEGER ()) 0 0 () (3 DEFERRED () () () () () ()) 0 () () 0 0)
75 'iend' 'datamodule' 'iend' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (INTEGER 8 0 0 INTEGER ())
0 0 () (1 DEFERRED () ()) 0 () () 0 0)
76 'iendcan' 'datamodule' 'iendcan' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () ()
0 () () 0 0)
77 'ii' 'datamodule' 'ii' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () () 0 () () 0 0)
78 'imidcan' 'datamodule' 'imidcan' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () ()
0 () () 0 0)
79 'intersectionflag' 'datamodule' 'intersectionflag' 1 ((VARIABLE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0
INTEGER ()) 0 0 () () 0 () () 0 0)
80 'inumbuild' 'datamodule' 'inumbuild' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () ()
0 () () 0 0)
81 'inumbuildneg' 'datamodule' 'inumbuildneg' 1 ((VARIABLE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0
INTEGER ()) 0 0 () () 0 () () 0 0)
82 'inumcanopy' 'datamodule' 'inumcanopy' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () ()
0 () () 0 0)
83 'istart' 'datamodule' 'istart' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (INTEGER 8 0 0
INTEGER ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
84 'istartcan' 'datamodule' 'istartcan' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () ()
0 () () 0 0)
85 'itermax' 'datamodule' 'itermax' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () ()
0 () () 0 0)
86 'j' 'datamodule' 'j' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN
EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () () 0 () () 0 0)
87 'jend' 'datamodule' 'jend' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (INTEGER 8 0 0 INTEGER ())
0 0 () (1 DEFERRED () ()) 0 () () 0 0)
88 'jendcan' 'datamodule' 'jendcan' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () ()
0 () () 0 0)
89 'jmidcan' 'datamodule' 'jmidcan' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () ()
0 () () 0 0)
90 'jstart' 'datamodule' 'jstart' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (INTEGER 8 0 0
INTEGER ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
91 'jstartcan' 'datamodule' 'jstartcan' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () ()
0 () () 0 0)
92 'k' 'datamodule' 'k' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN
EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () () 0 () () 0 0)
93 'kcantop' 'datamodule' 'kcantop' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (INTEGER 8 0 0
INTEGER ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
94 'kend' 'datamodule' 'kend' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (INTEGER 8 0 0 INTEGER ())
0 0 () (1 DEFERRED () ()) 0 () () 0 0)
95 'kref' 'datamodule' 'kref' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (INTEGER 8 0 0 INTEGER ())
0 0 () (1 DEFERRED () ()) 0 () () 0 0)
96 'kstart' 'datamodule' 'kstart' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (INTEGER 8 0 0
INTEGER ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
97 'lc' 'datamodule' 'lc' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
98 'leff' 'datamodule' 'leff' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
99 'lf' 'datamodule' 'lf' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
100 'logvel' 'datamodule' 'logvel' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 ()
() 0 0)
101 'lr' 'datamodule' 'lr' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
102 'lt' 'datamodule' 'lt' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
103 'lti' 'datamodule' 'lti' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
104 'lx' 'datamodule' 'lx' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
105 'ly' 'datamodule' 'ly' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
106 'lz' 'datamodule' 'lz' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
107 'm' 'datamodule' 'm' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(3 DEFERRED () () () () () ()) 0 () () 0 0)
108 'max_velmag' 'datamodule' 'max_velmag' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 ()
() 0 0)
109 'n' 'datamodule' 'n' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(3 DEFERRED () () () () () ()) 0 () () 0 0)
110 'num_new_builds' 'datamodule' 'num_new_builds' 1 ((VARIABLE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0
INTEGER ()) 0 0 () () 0 () () 0 0)
111 'num_sites' 'datamodule' 'num_sites' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () ()
0 () () 0 0)
112 'num_time_steps' 'datamodule' 'num_time_steps' 1 ((VARIABLE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0
INTEGER ()) 0 0 () () 0 () () 0 0)
113 'num_vert_points' 'datamodule' 'num_vert_points' 1 ((VARIABLE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0
INTEGER ()) 0 0 () () 0 () () 0 0)
114 'nx' 'datamodule' 'nx' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () () 0 () () 0 0)
115 'ny' 'datamodule' 'ny' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () () 0 () () 0 0)
116 'nz' 'datamodule' 'nz' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () () 0 () () 0 0)
117 'nz_data' 'datamodule' 'nz_data' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () ()
0 () () 0 0)
118 'o' 'datamodule' 'o' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(3 DEFERRED () () () () () ()) 0 () () 0 0)
119 'omegarelax' 'datamodule' 'omegarelax' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 ()
() 0 0)
120 'p' 'datamodule' 'p' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(3 DEFERRED () () () () () ()) 0 () () 0 0)
121 'p1' 'datamodule' 'p1' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(3 DEFERRED () () () () () ()) 0 () () 0 0)
122 'p2' 'datamodule' 'p2' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(3 DEFERRED () () () () () ()) 0 () () 0 0)
123 'phi' 'datamodule' 'phi' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
124 'phiprime' 'datamodule' 'phiprime' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
125 'pi' 'datamodule' 'pi' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
126 'pp' 'datamodule' 'pp' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
127 'q' 'datamodule' 'q' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(3 DEFERRED () () () () () ()) 0 () () 0 0)
128 'r' 'datamodule' 'r' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(3 DEFERRED () () () () () ()) 0 () () 0 0)
129 'rcx' 'datamodule' 'rcx' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
130 'residual_reduction' 'datamodule' 'residual_reduction' 1 ((VARIABLE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ())
0 0 () () 0 () () 0 0)
131 'roofflag' 'datamodule' 'roofflag' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () ()
0 () () 0 0)
132 'rooftop_flag' 'datamodule' 'rooftop_flag' 1 ((VARIABLE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION)
(INTEGER 8 0 0 INTEGER ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
133 'rscale' 'datamodule' 'rscale' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
134 'site_ac' 'datamodule' 'site_ac' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (2 DEFERRED () () () ()) 0 () () 0 0)
135 'site_blayer_flag' 'datamodule' 'site_blayer_flag' 1 ((VARIABLE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION)
(INTEGER 8 0 0 INTEGER ()) 0 0 () (2 DEFERRED () () () ()) 0 () () 0 0)
136 'site_h' 'datamodule' 'site_h' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (2 DEFERRED () () () ()) 0 () () 0 0)
137 'site_nz_data' 'datamodule' 'site_nz_data' 1 ((VARIABLE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION)
(INTEGER 8 0 0 INTEGER ()) 0 0 () (2 DEFERRED () () () ()) 0 () () 0 0)
138 'site_pp' 'datamodule' 'site_pp' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (2 DEFERRED () () () ()) 0 () () 0 0)
139 'site_rl' 'datamodule' 'site_rl' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (2 DEFERRED () () () ()) 0 () () 0 0)
140 'site_u_data' 'datamodule' 'site_u_data' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (3 DEFERRED () () () () () ()) 0 () () 0 0)
141 'site_v_data' 'datamodule' 'site_v_data' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (3 DEFERRED () () () () () ()) 0 () () 0 0)
142 'site_wd_data' 'datamodule' 'site_wd_data' 1 ((VARIABLE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION)
(REAL 8 0 0 REAL ()) 0 0 () (3 DEFERRED () () () () () ()) 0 () () 0 0)
143 'site_ws_data' 'datamodule' 'site_ws_data' 1 ((VARIABLE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION)
(REAL 8 0 0 REAL ()) 0 0 () (3 DEFERRED () () () () () ()) 0 () () 0 0)
144 'site_xcoord' 'datamodule' 'site_xcoord' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
145 'site_ycoord' 'datamodule' 'site_ycoord' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
146 'site_z_data' 'datamodule' 'site_z_data' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (3 DEFERRED () () () () () ()) 0 () () 0 0)
147 'sor_iter' 'datamodule' 'sor_iter' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () ()
0 () () 0 0)
148 'staggered_flag' 'datamodule' 'staggered_flag' 1 ((VARIABLE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0
INTEGER ()) 0 0 () () 0 () () 0 0)
149 'streetcanyonflag' 'datamodule' 'streetcanyonflag' 1 ((VARIABLE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0
INTEGER ()) 0 0 () () 0 () () 0 0)
150 'stretchgridflag' 'datamodule' 'stretchgridflag' 1 ((VARIABLE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0
INTEGER ()) 0 0 () () 0 () () 0 0)
151 'sx_east' 'datamodule' 'sx_east' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
152 'sx_west' 'datamodule' 'sx_west' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
153 'sy_north' 'datamodule' 'sy_north' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
154 'sy_south' 'datamodule' 'sy_south' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
155 'theta' 'datamodule' 'theta' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
156 'theta_init' 'datamodule' 'theta_init' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () ()
0 () () 0 0)
157 'time' 'datamodule' 'time' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
158 'u' 'datamodule' 'u' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(3 DEFERRED () () () () () ()) 0 () () 0 0)
159 'u_data' 'datamodule' 'u_data' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
160 'u_prof' 'datamodule' 'u_prof' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (2 DEFERRED () () () ()) 0 () () 0 0)
161 'uh' 'datamodule' 'uh' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
162 'uin' 'datamodule' 'uin' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
163 'umult' 'datamodule' 'umult' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
164 'umult_init' 'datamodule' 'umult_init' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 ()
() 0 0)
165 'uo' 'datamodule' 'uo' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(3 DEFERRED () () () () () ()) 0 () () 0 0)
166 'uo_bl' 'datamodule' 'uo_bl' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
167 'uo_ref' 'datamodule' 'uo_ref' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 ()
() 0 0)
168 'uo_roof' 'datamodule' 'uo_roof' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (3 DEFERRED () () () () () ()) 0 () () 0 0)
169 'uofield_flag' 'datamodule' 'uofield_flag' 1 ((VARIABLE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0
INTEGER ()) 0 0 () () 0 () () 0 0)
170 'uoint' 'datamodule' 'uoint' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
171 'uosensor_flag' 'datamodule' 'uosensor_flag' 1 ((VARIABLE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0
INTEGER ()) 0 0 () () 0 () () 0 0)
172 'upwindflag' 'datamodule' 'upwindflag' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () ()
0 () () 0 0)
173 'ustar' 'datamodule' 'ustar' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 ()
() 0 0)
174 'utmx' 'datamodule' 'utmx' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
175 'utmy' 'datamodule' 'utmy' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
176 'utmzone' 'datamodule' 'utmzone' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 ()
() 0 0)
177 'v' 'datamodule' 'v' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(3 DEFERRED () () () () () ()) 0 () () 0 0)
178 'v_data' 'datamodule' 'v_data' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
179 'v_prof' 'datamodule' 'v_prof' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (2 DEFERRED () () () ()) 0 () () 0 0)
180 'visc' 'datamodule' 'visc' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(3 DEFERRED () () () () () ()) 0 () () 0 0)
181 'vk' 'datamodule' 'vk' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
182 'vmult' 'datamodule' 'vmult' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
183 'vmult_init' 'datamodule' 'vmult_init' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 ()
() 0 0)
184 'vo' 'datamodule' 'vo' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(3 DEFERRED () () () () () ()) 0 () () 0 0)
185 'vo_bl' 'datamodule' 'vo_bl' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
186 'vo_ref' 'datamodule' 'vo_ref' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 ()
() 0 0)
187 'vo_roof' 'datamodule' 'vo_roof' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (3 DEFERRED () () () () () ()) 0 () () 0 0)
188 'voint' 'datamodule' 'voint' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
189 'w' 'datamodule' 'w' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(3 DEFERRED () () () () () ()) 0 () () 0 0)
190 'wakeflag' 'datamodule' 'wakeflag' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (INTEGER 8 0 0 INTEGER ()) 0 0 () ()
0 () () 0 0)
191 'wd_data' 'datamodule' 'wd_data' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
192 'weff' 'datamodule' 'weff' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
193 'wm' 'datamodule' 'wm' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(3 DEFERRED () () () () () ()) 0 () () 0 0)
194 'wms' 'datamodule' 'wms' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(3 DEFERRED () () () () () ()) 0 () () 0 0)
195 'wo' 'datamodule' 'wo' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(3 DEFERRED () () () () () ()) 0 () () 0 0)
196 'wprime' 'datamodule' 'wprime' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
197 'ws_data' 'datamodule' 'ws_data' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
198 'wt' 'datamodule' 'wt' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
199 'wti' 'datamodule' 'wti' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
200 'x_subdomain_end' 'datamodule' 'x_subdomain_end' 1 ((VARIABLE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ())
0 0 () () 0 () () 0 0)
201 'x_subdomain_start' 'datamodule' 'x_subdomain_start' 1 ((VARIABLE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ())
0 0 () () 0 () () 0 0)
202 'x_write' 'datamodule' 'x_write' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (3 DEFERRED () () () () () ()) 0 () () 0 0)
203 'xbo' 'datamodule' 'xbo' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
204 'xfo' 'datamodule' 'xfo' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
205 'xlo' 'datamodule' 'xlo' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
206 'xucan' 'datamodule' 'xucan' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 ()
() 0 0)
207 'xuo' 'datamodule' 'xuo' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
208 'xwcan' 'datamodule' 'xwcan' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 ()
() 0 0)
209 'y_subdomain_end' 'datamodule' 'y_subdomain_end' 1 ((VARIABLE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ())
0 0 () () 0 () () 0 0)
210 'y_subdomain_start' 'datamodule' 'y_subdomain_start' 1 ((VARIABLE
UNKNOWN-INTENT UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ())
0 0 () () 0 () () 0 0)
211 'y_write' 'datamodule' 'y_write' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (3 DEFERRED () () () () () ()) 0 () () 0 0)
212 'ybo' 'datamodule' 'ybo' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
213 'yfo' 'datamodule' 'yfo' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
214 'ylo' 'datamodule' 'ylo' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
215 'yucan' 'datamodule' 'yucan' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 ()
() 0 0)
216 'yuo' 'datamodule' 'yuo' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
217 'ywcan' 'datamodule' 'ywcan' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 ()
() 0 0)
218 'z' 'datamodule' 'z' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
219 'z_data' 'datamodule' 'z_data' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
220 'z_write' 'datamodule' 'z_write' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (3 DEFERRED () () () () () ()) 0 () () 0 0)
221 'zd' 'datamodule' 'zd' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
222 'zfo' 'datamodule' 'zfo' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
223 'zfo_actual' 'datamodule' 'zfo_actual' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0
REAL ()) 0 0 () (1 DEFERRED () ()) 0 () () 0 0)
224 'zm' 'datamodule' 'zm' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ()) 0 0 ()
(1 DEFERRED () ()) 0 () () 0 0)
225 'zo' 'datamodule' 'zo' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
226 'zref' 'datamodule' 'zref' 1 ((VARIABLE UNKNOWN-INTENT UNKNOWN-PROC
UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 () () 0 0)
227 'zucan' 'datamodule' 'zucan' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 ()
() 0 0)
228 'zwcan' 'datamodule' 'zwcan' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN EXPLICIT-SAVE) (REAL 8 0 0 REAL ()) 0 0 () () 0 ()
() 0 0)
)

('a' 0 2 'aa' 0 3 'abse' 0 4 'ac' 0 5 'alpha1' 0 6 'alpha2' 0 7 'atten'
0 8 'az' 0 9 'b' 0 10 'bb' 0 11 'bldnum' 0 12 'bldtype' 0 13 'build_uin'
0 14 'bz' 0 15 'ca' 0 16 'canopy_atten' 0 17 'canopy_d' 0 18 'canopy_ktop'
0 19 'canopy_top' 0 20 'canopy_ustar' 0 21 'canopy_zo' 0 22 'celltype' 0
23 'cgamma' 0 24 'cgroup' 0 25 'ch' 0 26 'cl' 0 27 'cnum' 0 28 'cpbaucan'
0 29 'cpbawcan' 0 30 'cpbbeta' 0 31 'cpbk' 0 32 'ctype' 0 33 'cw' 0 34
'cxfo' 0 35 'cyfo' 0 36 'czfo' 0 37 'd' 0 38 'datamodule' 0 39 'denoms'
0 40 'diffiter' 0 41 'diffstep' 0 42 'diffusion_flag' 0 43
'domain_rotation' 0 44 'dt' 0 45 'dx' 0 46 'dy' 0 47 'dz' 0 48 'dz_array'
0 49 'e' 0 50 'eps' 0 51 'eta' 0 52 'f' 0 53 'fdh' 0 54 'format_flag' 0
55 'fxd' 0 56 'fyd' 0 57 'fzd' 0 58 'g' 0 59 'gamma' 0 60 'group_id' 0
61 'h' 0 62 'havx' 0 63 'havy' 0 64 'hdifx' 0 65 'hdify' 0 66 'hlowx' 0
67 'hlowy' 0 68 'ht' 0 69 'i' 0 70 'i_time' 0 71 'ibldflag' 0 72 'ibuild'
0 73 'icellflag' 0 74 'iend' 0 75 'iendcan' 0 76 'ii' 0 77 'imidcan' 0
78 'intersectionflag' 0 79 'inumbuild' 0 80 'inumbuildneg' 0 81
'inumcanopy' 0 82 'istart' 0 83 'istartcan' 0 84 'itermax' 0 85 'j' 0 86
'jend' 0 87 'jendcan' 0 88 'jmidcan' 0 89 'jstart' 0 90 'jstartcan' 0 91
'k' 0 92 'kcantop' 0 93 'kend' 0 94 'kref' 0 95 'kstart' 0 96 'lc' 0 97
'leff' 0 98 'lf' 0 99 'logvel' 0 100 'lr' 0 101 'lt' 0 102 'lti' 0 103
'lx' 0 104 'ly' 0 105 'lz' 0 106 'm' 0 107 'max_velmag' 0 108 'n' 0 109
'num_new_builds' 0 110 'num_sites' 0 111 'num_time_steps' 0 112
'num_vert_points' 0 113 'nx' 0 114 'ny' 0 115 'nz' 0 116 'nz_data' 0 117
'o' 0 118 'omegarelax' 0 119 'p' 0 120 'p1' 0 121 'p2' 0 122 'phi' 0 123
'phiprime' 0 124 'pi' 0 125 'pp' 0 126 'q' 0 127 'r' 0 128 'rcx' 0 129
'residual_reduction' 0 130 'roofflag' 0 131 'rooftop_flag' 0 132 'rscale'
0 133 'site_ac' 0 134 'site_blayer_flag' 0 135 'site_h' 0 136
'site_nz_data' 0 137 'site_pp' 0 138 'site_rl' 0 139 'site_u_data' 0 140
'site_v_data' 0 141 'site_wd_data' 0 142 'site_ws_data' 0 143
'site_xcoord' 0 144 'site_ycoord' 0 145 'site_z_data' 0 146 'sor_iter' 0
147 'staggered_flag' 0 148 'streetcanyonflag' 0 149 'stretchgridflag' 0
150 'sx_east' 0 151 'sx_west' 0 152 'sy_north' 0 153 'sy_south' 0 154
'theta' 0 155 'theta_init' 0 156 'time' 0 157 'u' 0 158 'u_data' 0 159
'u_prof' 0 160 'uh' 0 161 'uin' 0 162 'umult' 0 163 'umult_init' 0 164
'uo' 0 165 'uo_bl' 0 166 'uo_ref' 0 167 'uo_roof' 0 168 'uofield_flag' 0
169 'uoint' 0 170 'uosensor_flag' 0 171 'upwindflag' 0 172 'ustar' 0 173
'utmx' 0 174 'utmy' 0 175 'utmzone' 0 176 'v' 0 177 'v_data' 0 178
'v_prof' 0 179 'visc' 0 180 'vk' 0 181 'vmult' 0 182 'vmult_init' 0 183
'vo' 0 184 'vo_bl' 0 185 'vo_ref' 0 186 'vo_roof' 0 187 'voint' 0 188 'w'
0 189 'wakeflag' 0 190 'wd_data' 0 191 'weff' 0 192 'wm' 0 193 'wms' 0
194 'wo' 0 195 'wprime' 0 196 'ws_data' 0 197 'wt' 0 198 'wti' 0 199
'x_subdomain_end' 0 200 'x_subdomain_start' 0 201 'x_write' 0 202 'xbo'
0 203 'xfo' 0 204 'xlo' 0 205 'xucan' 0 206 'xuo' 0 207 'xwcan' 0 208
'y_subdomain_end' 0 209 'y_subdomain_start' 0 210 'y_write' 0 211 'ybo'
0 212 'yfo' 0 213 'ylo' 0 214 'yucan' 0 215 'yuo' 0 216 'ywcan' 0 217 'z'
0 218 'z_data' 0 219 'z_write' 0 220 'zd' 0 221 'zfo' 0 222 'zfo_actual'
0 223 'zm' 0 224 'zo' 0 225 'zref' 0 226 'zucan' 0 227 'zwcan' 0 228)
